development:
  adapter: mysql2
  database: sortable_nested_set_development
  host: localhost
  username: root
  password: qwerty
  encoding: utf8
  timeout: 5000

production:
  adapter: mysql2
  database: sortable_nested_set_production
  host: localhost
  username: root
  password: qwerty
  encoding: utf8
  timeout: 5000
